// Code generated by go-swagger; DO NOT EDIT.

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetIPCacheHandlerFunc turns a function with the right signature into a get IP cache handler
type GetIPCacheHandlerFunc func(GetIPCacheParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIPCacheHandlerFunc) Handle(params GetIPCacheParams) middleware.Responder {
	return fn(params)
}

// GetIPCacheHandler interface for that can handle valid get IP cache params
type GetIPCacheHandler interface {
	Handle(GetIPCacheParams) middleware.Responder
}

// NewGetIPCache creates a new http.Handler for the get IP cache operation
func NewGetIPCache(ctx *middleware.Context, handler GetIPCacheHandler) *GetIPCache {
	return &GetIPCache{Context: ctx, Handler: handler}
}

/*GetIPCache swagger:route GET /ip/cache/ policy getIpCache

Lists IP cache entries

Retrieves a list of IP cache entries, optionally filtered on the key by
a CIDR IP range


*/
type GetIPCache struct {
	Context *middleware.Context
	Handler GetIPCacheHandler
}

func (o *GetIPCache) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetIPCacheParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
