// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// IPCacheEntryK8sMetadata Kubernetes Metadata of an IP cache entry
// swagger:model IPCacheEntryK8sMetadata
type IPCacheEntryK8sMetadata struct {

	// Namespace of the Kubernetes pod of the IP
	Namespace string `json:"namespace,omitempty"`

	// Name of the Kubernetes pod of the IP
	PodName string `json:"podName,omitempty"`
}

// Validate validates this IP cache entry k8s metadata
func (m *IPCacheEntryK8sMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPCacheEntryK8sMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPCacheEntryK8sMetadata) UnmarshalBinary(b []byte) error {
	var res IPCacheEntryK8sMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
